kind: Service
apiVersion: v1
metadata:
  name: glpi
  labels:
    name: glpi
spec:
  selector:
    app: glpi
  ports:
  - protocol: TCP
    port: 9000
    #nodePort: 30100
    targetPort: 9000
  #type: NodePort
