kind: Service
apiVersion: v1
metadata:
  name: glpi-svc
  labels:
    name: glpi-svc
spec:
  selector:
    app: glpi
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30100
    targetPort: 9000
  type: NodePort
