apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
#  publicIPs: 
#    - 12.0.0.5 # IP который будет присвоен сервису помимо автоматически назначенного.
  type: NodePort
  ports:
    - name: http
      port: 80 #порт на котором будет слушать сервис
      targetPort: 80 #порт контейнера на который будет производиться трансляция запросов
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    name: nginx # поле должно совпадать с аналогичным в конфиге ReplicationController
