apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
spec:
  template:
    metadata:
      name: mysql-init
    spec:
      containers:
      - name: mysql-init
        image: mysql:latest
        command: ["mysql"]
        args: ["-hmysql","-uroot","-proot","-Dmysql","-e","create database glpi; grant all privileges on glpi.* to 'glpi'@'%' identified by 'glpi';"]
      restartPolicy: Never
